[package]
name = "game"
version = "0.1.0"
authors = ["tglanz"]
edition = "2018"

[dependencies]
amethyst = "0.10.0"
log = { version = "0.4.6", features = ["serde"] }
serde = "1.0"
serde_derive = "1.0"